/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AIChatBox: typeof import('./src/components/AI/AIChatBox.vue')['default']
    AIMessage: typeof import('./src/components/AI/AIMessage.vue')['default']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuDivider: typeof import('ant-design-vue/es')['MenuDivider']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AppLayout: typeof import('./src/components/Layout/AppLayout.vue')['default']
    ChatInput: typeof import('./src/components/AI/ChatInput.vue')['default']
    ConfirmCard: typeof import('./src/components/AI/Cards/ConfirmCard.vue')['default']
    FormCard: typeof import('./src/components/AI/Cards/FormCard.vue')['default']
    Header: typeof import('./src/components/Layout/Header.vue')['default']
    Loading: typeof import('./src/components/Common/Loading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectCard: typeof import('./src/components/AI/Cards/SelectCard.vue')['default']
    Sidebar: typeof import('./src/components/Layout/Sidebar.vue')['default']
    ThemeSwitch: typeof import('./src/components/Common/ThemeSwitch.vue')['default']
    UploadCard: typeof import('./src/components/AI/Cards/UploadCard.vue')['default']
    UserMessage: typeof import('./src/components/AI/UserMessage.vue')['default']
  }
}
